module.exports = {
	UHS500_BUS: [
		{ id: '01', label: 'ME1PGM' },
		{ id: '02', label: 'ME1PVW' },
		{ id: '03', label: 'ME1KEY1-F' },
		{ id: '04', label: 'ME1KEY1-S' },
		{ id: '05', label: 'ME1KEY2-F' },
		{ id: '06', label: 'ME1KEY2-S' },
		{ id: '07', label: 'ME1KEY3-F' },
		{ id: '08', label: 'ME1KEY3-S' },
		{ id: '97', label: 'DSK1-F' },
		{ id: '98', label: 'DSK1-S' },
		{ id: '99', label: 'DSK2-F' },
		{ id: '100', label: 'DSK2-S' },
		{ id: '113', label: 'AUX 1' },
		{ id: '114', label: 'AUX 2' },
		{ id: '115', label: 'AUX 3' },
		{ id: '116', label: 'AUX 4' },
		{ id: '141', label: 'DISP' },
		{ id: '150', label: 'VMEM-V' },
		{ id: '151', label: 'VMEM-K' },
		{ id: '153', label: 'MV1-1' },
		{ id: '168', label: 'MV1-16' },
		{ id: '169', label: 'MV2-1' },
		{ id: '184', label: 'MV2-16' },
	],
	
	HS410_BUS: [
		{ id: '02', label: 'PGM' },
		{ id: '03', label: 'PVW' },
		{ id: '00', label: 'Bus A' },
		{ id: '01', label: 'Bus B' },
		{ id: '04', label: 'Key Fill' },
		{ id: '05', label: 'Key Source' },
		{ id: '06', label: 'DSK Fill' },
		{ id: '07', label: 'DSK Source' },
		{ id: '10', label: 'PinP 1' },
		{ id: '11', label: 'PinP 2' },
		{ id: '12', label: 'Aux 1' },
		{ id: '13', label: 'Aux 2' },
		{ id: '14', label: 'Aux 3' },
		{ id: '15', label: 'Aux 4' },
	],
	
	HS50_BUS: [
		{ id: '02', label: 'PGM' },
		{ id: '03', label: 'PVW' },
		{ id: '00', label: 'Bus A' },
		{ id: '01', label: 'Bus B' },
		{ id: '04', label: 'Key Fill' },
		{ id: '05', label: 'Key Source' },
		{ id: '10', label: 'PinP' },
		{ id: '12', label: 'Aux' },
	],
	
	UHS500_INPUTS: [
		{ id: '01', label: 'IN1' },
		{ id: '02', label: 'IN2' },
		{ id: '03', label: 'SDI IN3' },
		{ id: '04', label: 'SDI IN4' },
		{ id: '05', label: 'SDI IN5' },
		{ id: '06', label: 'SDI IN6' },
		{ id: '07', label: 'SDI IN7' },
		{ id: '08', label: 'SDI IN8' },
		{ id: '09', label: 'OPA IN1' },
		{ id: '10', label: 'OPA IN2' },
		{ id: '11', label: 'OPA IN3' },
		{ id: '12', label: 'OPA IN4' },
		{ id: '13', label: 'OPB IN1' },
		{ id: '14', label: 'OPB IN2' },
		{ id: '15', label: 'OPB IN3' },
		{ id: '16', label: 'OPB IN4' },
		{ id: '145', label: 'CBGD 1' },
		{ id: '146', label: 'CBGD 2' },
		{ id: '147', label: 'CBAR' },
		{ id: '148', label: 'BLACK' },
		{ id: '149', label: 'STILL1-V' },
		{ id: '150', label: 'STILL1-K' },
		{ id: '151', label: 'STILL2-V' },
		{ id: '152', label: 'STILL2-K' },
		{ id: '157', label: 'CLIP1-V' },
		{ id: '158', label: 'CLIP1-K' },
		{ id: '159', label: 'CLIP2-V' },
		{ id: '160', label: 'CLIP2-K' },
		{ id: '165', label: 'MV 1' },
		{ id: '166', label: 'MV 2' },
		{ id: '171', label: 'KEY OUT' },
		{ id: '172', label: 'CLN' },
		{ id: '201', label: 'PGM' },
		{ id: '203', label: 'PVW' },
		{ id: '209', label: 'ME PGM' },
		{ id: '227', label: 'AUX 1' },
		{ id: '228', label: 'AUX 2' },
		{ id: '229', label: 'AUX 3' },
		{ id: '230', label: 'AUX 4' },
		{ id: '251', label: 'CLOCK' },
	],
	
	HS410_INPUTS: [
		{ id: '00', label: 'XPT 1' },
		{ id: '01', label: 'XPT 2' },
		{ id: '02', label: 'XPT 3' },
		{ id: '03', label: 'XPT 4' },
		{ id: '04', label: 'XPT 5' },
		{ id: '05', label: 'XPT 6' },
		{ id: '06', label: 'XPT 7' },
		{ id: '07', label: 'XPT 8' },
		{ id: '08', label: 'XPT 9' },
		{ id: '09', label: 'XPT 10' },
		{ id: '10', label: 'XPT 11' },
		{ id: '11', label: 'XPT 12' },
		{ id: '12', label: 'XPT 13' },
		{ id: '13', label: 'XPT 14' },
		{ id: '14', label: 'XPT 15' },
		{ id: '15', label: 'XPT 16' },
		{ id: '16', label: 'XPT 17' },
		{ id: '17', label: 'XPT 18' },
		{ id: '18', label: 'XPT 19' },
		{ id: '19', label: 'XPT 20' },
		{ id: '20', label: 'XPT 21' },
		{ id: '21', label: 'XPT 22' },
		{ id: '22', label: 'XPT 23' },
		{ id: '23', label: 'XPT 24' },
		{ id: '50', label: 'Input 1' },
		{ id: '51', label: 'Input 2' },
		{ id: '52', label: 'Input 3' },
		{ id: '53', label: 'Input 4' },
		{ id: '54', label: 'Input 5' },
		{ id: '55', label: 'Input 6' },
		{ id: '56', label: 'Input 7' },
		{ id: '57', label: 'Input 8' },
		{ id: '58', label: 'Input 9' },
		{ id: '59', label: 'Input 10' },
		{ id: '60', label: 'Input 11' },
		{ id: '61', label: 'Input 12' },
		{ id: '62', label: 'Input 13' },
		{ id: '70', label: 'Color bars' },
		{ id: '71', label: 'Color background 1' },
		{ id: '96', label: 'Color background 2' },
		{ id: '72', label: 'Black' },
		{ id: '73', label: 'Still1V' },
		{ id: '74', label: 'Still2V' },
		{ id: '75', label: 'Clip1V' },
		{ id: '76', label: 'Clip2V' },
		{ id: '77', label: 'PGM' },
		{ id: '78', label: 'PVW' },
		{ id: '79', label: 'KeyOut' },
		{ id: '80', label: 'CLN' },
		{ id: '81', label: 'Multi view' },
		{ id: '91', label: 'M-PVW' },
		{ id: '92', label: 'Still1K' },
		{ id: '93', label: 'Still2K' },
		{ id: '94', label: 'Clip1K' },
		{ id: '95', label: 'Clip2K' },
		{ id: '99', label: 'No selection' },
	],
	
	HS50_INPUTS: [
		{ id: '00', label: 'XPT 1' },
		{ id: '01', label: 'XPT 2' },
		{ id: '02', label: 'XPT 3' },
		{ id: '03', label: 'XPT 4' },
		{ id: '04', label: 'XPT 5' },
		{ id: '05', label: 'XPT 6' },
		{ id: '06', label: 'XPT 7' },
		{ id: '07', label: 'XPT 8' },
		{ id: '08', label: 'XPT 9' },
		{ id: '09', label: 'XPT 10' },
		{ id: '50', label: 'Input 1' },
		{ id: '51', label: 'Input 2' },
		{ id: '52', label: 'Input 3' },
		{ id: '53', label: 'Input 4' },
		{ id: '54', label: 'Input 5' },
		{ id: '70', label: 'Color bars' },
		{ id: '71', label: 'Color background' },
		{ id: '72', label: 'Black' },
		{ id: '73', label: 'Frame memory 1' },
		{ id: '74', label: 'Frame memory 2' },
		{ id: '77', label: 'PGM' },
		{ id: '78', label: 'PVW' },
		{ id: '79', label: 'KeyOut' },
		{ id: '80', label: 'CLN' },
		{ id: '81', label: 'Multi view' },
	],
	
	UHS500_TARGETS: [
		{ id: '00', label: 'BKGD' },
		{ id: '01', label: 'KEY 1' },
		{ id: '04', label: 'KEY 2' },
		{ id: '05', label: 'KEY 3' },
		{ id: '06', label: 'FTB' },
		{ id: '07', label: 'DSK 1' },
		{ id: '08', label: 'DSK 2' },
	],
	
	HS410_TARGETS: [
		{ id: '00', label: 'BKGD' },
		{ id: '01', label: 'KEY' },
		{ id: '04', label: 'PinP 1' },
		{ id: '05', label: 'PinP 2' },
		{ id: '06', label: 'FTB' },
		{ id: '07', label: 'DSK' },
	],
	
	HS50_TARGETS: [
		{ id: '00', label: 'BKGD' },
		{ id: '01', label: 'KEY' },
		{ id: '04', label: 'PinP' },
		{ id: '06', label: 'FTB' },
	],
	
	UHS500_CUTTARGETS: [
		{ id: '00', label: 'BKGD' },
		{ id: '01', label: 'KEY 1' },
		{ id: '04', label: 'KEY 2' },
		{ id: '05', label: 'KEY 3' },
		{ id: '06', label: 'FTB' },
		{ id: '07', label: 'DSK 1' },
		{ id: '08', label: 'DSK 2' },
	],
	
	HS410_CUTTARGETS: [
		{ id: '00', label: 'BKGD' },
		{ id: '01', label: 'KEY' },
		{ id: '04', label: 'PinP 1' },
		{ id: '05', label: 'PinP 2' },
		{ id: '06', label: 'FTB' },
		{ id: '07', label: 'DSK' },
	],
	
	HS50_CUTTARGETS: [
		{ id: '00', label: 'BKGD' },
		{ id: '01', label: 'KEY' },
	]
}